Lab No. 2 – Fashion MNIST
Write a program in Python to recognize 
Fashion items using the Fashion-MNIST Dataset

In [1]:
# Import libraries
import pandas as pd
import numpy as np

In [2]:
# Import data
train_df = pd.read_csv("Files/FMNIST/fashion-mnist_train.csv")
test_df = pd.read_csv("Files/FMNIST/fashion-mnist_test.csv")

In [3]:
# Exploratory analysis of data
train_df.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      2       0       0       0       0       0       0       0       0   
1      9       0       0       0       0       0       0       0       0   
2      6       0       0       0       0       0       0       0       5   
3      0       0       0       0       1       2       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0        30        43         0   
3       0  ...         3         0         0         0         0         1   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 785 entries, label to pixel784
dtypes: int64(785)
memory usage: 359.3 MB


In [5]:
train_df.describe()

label        pixel1        pixel2        pixel3        pixel4  \
count  60000.000000  60000.000000  60000.000000  60000.000000  60000.000000   
mean       4.500000      0.000900      0.006150      0.035333      0.101933   
std        2.872305      0.094689      0.271011      1.222324      2.452871   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000      0.000000      0.000000      0.000000      0.000000   
50%        4.500000      0.000000      0.000000      0.000000      0.000000   
75%        7.000000      0.000000      0.000000      0.000000      0.000000   
max        9.000000     16.000000     36.000000    226.000000    164.000000   

             pixel5        pixel6        pixel7        pixel8        pixel9  \
count  60000.000000  60000.000000  60000.000000  60000.000000  60000.000000   
mean       0.247967      0.411467      0.805767      2.198283      5.682000   
std        4.306912      5.836188      8.215169     14.093378     23.819481   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max      227.000000    230.000000    224.000000    255.000000    254.000000   

       ...      pixel775      pixel776      pixel777      pixel778  \
count  ...  60000.000000  60000.000000  60000.000000  60000.000000   
mean   ...     34.625400     23.300683     16.588267     17.869433   
std    ...     57.545242     48.854427     41.979611     43.966032   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      0.000000      0.000000      0.000000   
75%    ...     58.000000      9.000000      0.000000      0.000000   
max    ...    255.000000    255.000000    255.000000    255.000000   

           pixel779      pixel780      pixel781      pixel782      pixel783  \
count  60000.000000  60000.000000  60000.000000  60000.000000  60000.000000   
mean      22.814817     17.911483      8.520633      2.753300      0.855517   
std       51.830477     45.149388     29.614859     17.397652      9.356960   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max      255.000000    255.000000    255.000000    255.000000    255.000000   

          pixel784  
count  60000.00000  
mean       0.07025  
std        2.12587  
min        0.00000  
25%        0.00000  
50%        0.00000  
75%        0.00000  
max      170.00000  

[8 rows x 785 columns]

In [ ]:
# Data cleanup (If necessary)

In [6]:
# Data Preprocessing
y_train = train_df.pop("label")
y_test = test_df.pop("label")

In [7]:
y_train

0        2
1        9
2        6
3        0
4        3
        ..
59995    9
59996    1
59997    8
59998    8
59999    7
Name: label, Length: 60000, dtype: int64

In [8]:
X_train = np.array(train_df)
X_test= np.array(test_df)

In [9]:
# Models
# Logistic Regression
from sklearn.linear_model import LogisticRegression
fashion_logistic = LogisticRegression()
# Model training
fashion_logistic.fit(X_train,y_train)

C:\Users\dpint\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [10]:
# Support Vector Machine
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
fashion_svm = make_pipeline(StandardScaler(), LinearSVC(random_state=0, tol=1e-5))
# Model Training
fashion_svm.fit(X_train,y_train)

C:\Users\dpint\anaconda3\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearsvc', LinearSVC(random_state=0, tol=1e-05))])

In [11]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
fashion_randForest = RandomForestClassifier(n_estimators=10)
fashion_randForest.fit(X_train,y_train)

RandomForestClassifier(n_estimators=10)

In [ ]:
# Neural Network (MLP)


In [ ]:
# Convolutional Neural Network (CNN)

In [12]:
# Data Prediction
# Logistic Regression
fy_predict_logistic = fashion_logistic.predict(X_test)
# Support Vector Machine
fy_predict_svm = fashion_svm.predict(X_test)
# Random Forest
fy_predict_randForest = fashion_randForest.predict(X_test)

In [29]:
fy_predict_logistic[:10]

array([0, 1, 2, 0, 4, 6, 8, 6, 5, 0], dtype=int64)

In [13]:
fy_predict_svm[:10]

array([0, 1, 2, 2, 3, 3, 8, 6, 5, 0], dtype=int64)

In [14]:
fy_predict_randForest[:10]

array([0, 1, 2, 6, 3, 6, 8, 6, 5, 0], dtype=int64)

In [ ]:
# Result Visualization

In [15]:
# Performance evaluation
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [16]:
log_cv = cross_val_score(fashion_logistic, X_train, y_train, cv=3, scoring="accuracy")

C:\Users\dpint\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\dpint\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.8489, 0.8491, 0.8486])

In [20]:
accuracy = [accuracy_score(y_test, fy_predict_logistic),
            accuracy_score(y_test, fy_predict_svm),
            accuracy_score(y_test, fy_predict_randForest)]
precision = [precision_score(y_test, fy_predict_logistic, average='macro'),
             precision_score(y_test, fy_predict_svm, average='macro'),
             precision_score(y_test, fy_predict_randForest, average='macro')]
recall = [recall_score(y_test, fy_predict_logistic, average='micro'),
         recall_score(y_test, fy_predict_svm, average='micro'),
         recall_score(y_test, fy_predict_randForest, average='micro')]
f1 = [f1_score(y_test, fy_predict_logistic, average = 'weighted'),
     f1_score(y_test, fy_predict_svm, average = 'weighted'),
     f1_score(y_test, fy_predict_randForest, average = 'weighted')]
perf_metrics = pd.DataFrame(data = [accuracy,precision,recall,f1], columns = ["Logistic",
                                                                              "SVM", "RandForest"],
                           index = ["Accuracy","Precision","Recall","F1"])


In [21]:
perf_metrics

Logistic       SVM  RandForest
Accuracy   0.854400  0.837400    0.859600
Precision  0.852756  0.835033    0.858368
Recall     0.854400  0.837400    0.859600
F1         0.852901  0.835790    0.857924